// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM25OM2JQqJMqCxT8A2ZtGpkpGlj46WqI',
    appId: '1:532039303436:web:ed99cec974012c8280c929',
    messagingSenderId: '532039303436',
    projectId: 'flutter-photo-sharing-ap-efddf',
    authDomain: 'flutter-photo-sharing-ap-efddf.firebaseapp.com',
    storageBucket: 'flutter-photo-sharing-ap-efddf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWvlZmUjWYvGeWuEGokIgRlEFXtlx4Xw',
    appId: '1:532039303436:android:12d50fec354b8b3d80c929',
    messagingSenderId: '532039303436',
    projectId: 'flutter-photo-sharing-ap-efddf',
    storageBucket: 'flutter-photo-sharing-ap-efddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZuZXSV_Qqw65m8JUuK9sdQLEf8z0A04',
    appId: '1:532039303436:ios:7e22cc2b8abe3a1480c929',
    messagingSenderId: '532039303436',
    projectId: 'flutter-photo-sharing-ap-efddf',
    storageBucket: 'flutter-photo-sharing-ap-efddf.appspot.com',
    iosClientId: '532039303436-cinvi834g0j9a1d1qmookstmr8uoeqpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2flutterphotosharingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPZuZXSV_Qqw65m8JUuK9sdQLEf8z0A04',
    appId: '1:532039303436:ios:a78c5b51d762601280c929',
    messagingSenderId: '532039303436',
    projectId: 'flutter-photo-sharing-ap-efddf',
    storageBucket: 'flutter-photo-sharing-ap-efddf.appspot.com',
    iosClientId: '532039303436-4468k87e9li7cs1rl3r5nsdajc6u6cnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2flutterphotosharingapp.RunnerTests',
  );
}
